[build]
builder = "NIXPACKS"
buildCommand = "pip install -r backend/requirements.txt && cd backend && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd backend && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
watchPatterns = ["backend/**"]

[env]
NIXPACKS_PYTHON_VERSION = "3.11"